/**
 * Dữ liệu mẫu Cherry House — 10 cơ sở Bắc → Nam, chi nhánh 1–2/cơ sở.
 */

const IMG = {
  hero1: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
  hero2: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
  hero3: 'https://images.unsplash.com/photo-1560448204-e02f11c45751?auto=format&fit=crop&w=1200&q=80',
  hero4: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
  room: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80',
};

/** Số chi nhánh mỗi cơ sở (1 hoặc 2) — cố định để seed tái lập được */
const BRANCH_COUNTS = [2, 1, 1, 2, 1, 2, 1, 2, 1, 2];

const PROPERTIES = [
  {
    slug: 'cherry-house-ha-noi',
    name: 'Cherry House Hà Nội',
    city: 'Hà Nội',
    region: 'Hà Nội',
    kind: 'homestay',
    tagline: 'Homestay giữa lòng phố cổ & khu diplomatic',
    description: 'Cherry House Hà Nội — không gian nghỉ dưỡng ấm cúng gần Hồ Hoàn Kiếm và các khu phố ngoại giao.',
    address: 'Quận Hoàn Kiếm, TP. Hà Nội',
    priceFromVnd: 750_000,
    rating: 4.7,
    reviewCount: 412,
    heroImageUrl: IMG.hero2,
    highlights: ['Gần Hồ Gươm', 'Check-in linh hoạt', 'Phù hợp công tác ngắn ngày'],
    branches: [
      { code: 'hn-hk', name: 'Chi nhánh Hoàn Kiếm', address: 'P. Hàng Gai, Hoàn Kiếm', tagline: 'Gần phố cổ, đi bộ tới Hồ Gươm', price: 750_000, roomCount: 8, lat: 21.0285, lng: 105.8542, imgUrl: IMG.hero2 },
      { code: 'hn-tayho', name: 'Chi nhánh Tây Hồ', address: 'P. Quảng An, Tây Hồ', tagline: 'View hồ Tây, không gian yên', price: 890_000, roomCount: 6, lat: 21.0663, lng: 105.8188, imgUrl: IMG.hero1 },
    ],
  },
  {
    slug: 'cherry-house-sapa',
    name: 'Cherry House Sa Pa',
    city: 'Sa Pa',
    region: 'Lào Cai',
    kind: 'homestay',
    tagline: 'View núi Fansipan — không khí trong lành',
    description: 'Homestay Cherry House tại Sa Pa, phù hợp trek và nghỉ cuối tuần miền núi.',
    address: 'TT. Sa Pa, Lào Cai',
    priceFromVnd: 680_000,
    rating: 4.6,
    reviewCount: 198,
    heroImageUrl: IMG.hero3,
    highlights: ['View thung lũng', 'Bữa sáng địa phương'],
    branches: [
      { code: 'sp-center', name: 'Cherry Sa Pa Trung tâm', address: 'Đường Cầu Mây, Sa Pa', tagline: 'Gần chợ & quảng trường', price: 680_000, roomCount: 10, lat: 22.3364, lng: 103.8438, imgUrl: IMG.hero3 },
    ],
  },
  {
    slug: 'cherry-retreat-ninh-binh',
    name: 'Cherry Retreat Ninh Bình',
    city: 'Ninh Bình',
    region: 'Ninh Bình',
    kind: 'villa',
    tagline: 'Villa view sông Ngô Đồng & Tràng An',
    description: 'Khu villa nghỉ dưỡng Cherry House tại Ninh Bình — lý tưởng cho nhóm và gia đình.',
    address: 'Huyện Hoa Lư, Ninh Bình',
    priceFromVnd: 2_400_000,
    rating: 4.8,
    reviewCount: 87,
    heroImageUrl: IMG.hero4,
    highlights: ['Hồ bơi riêng', 'Tour Tràng An'],
    branches: [
      { code: 'nb-trangan', name: 'Villa Tràng An', address: 'Khu du lịch Tràng An', tagline: 'Nguyên căn, sân vườn rộng', price: 2_400_000, roomCount: 2, lat: 20.2523, lng: 105.9745, imgUrl: IMG.hero4 },
    ],
  },
  {
    slug: 'cherry-house-da-nang',
    name: 'Cherry House Đà Nẵng',
    city: 'Đà Nẵng',
    region: 'Đà Nẵng',
    kind: 'mini_hotel',
    tagline: 'Mini stay gần biển Mỹ Khê & sông Hàn',
    description: 'Cherry House Đà Nẵng — mini hotel tiện nghi giữa biển và trung tâm thành phố.',
    address: 'Quận Sơn Trà & Ngũ Hành Sơn, Đà Nẵng',
    priceFromVnd: 920_000,
    rating: 4.7,
    reviewCount: 256,
    heroImageUrl: IMG.hero1,
    highlights: ['Gần biển', 'Hồ bơi rooftop'],
    branches: [
      { code: 'dn-mykhe', name: 'Chi nhánh Mỹ Khê', address: 'P. Phước Mỹ, Sơn Trà', tagline: 'Cách biển 5 phút đi bộ', price: 920_000, roomCount: 12, lat: 16.0471, lng: 108.2462, imgUrl: IMG.hero1 },
      { code: 'dn-han', name: 'Chi nhánh Sông Hàn', address: 'P. An Hải, Sơn Trà', tagline: 'View cầu Rồng về đêm', price: 1_050_000, roomCount: 10, lat: 16.0617, lng: 108.2275, imgUrl: IMG.hero2 },
    ],
  },
  {
    slug: 'cherry-house-hoi-an',
    name: 'Cherry House Hội An',
    city: 'Hội An',
    region: 'Quảng Nam',
    kind: 'homestay',
    tagline: 'Homestay phố cổ — đèn lồng & sông Thu Bồn',
    description: 'Nghỉ tại phố cổ Hội An với phong cách Cherry House — yên tĩnh, gần các hội quán.',
    address: 'TP. Hội An, Quảng Nam',
    priceFromVnd: 820_000,
    rating: 4.9,
    reviewCount: 341,
    heroImageUrl: IMG.hero3,
    highlights: ['Gần phố cổ', 'Xe đạp miễn phí'],
    branches: [
      { code: 'ha-oldtown', name: 'Chi nhánh Phố cổ', address: 'P. Minh An, Hội An', tagline: 'Trong lõi phố cổ', price: 820_000, roomCount: 9, lat: 15.8774, lng: 108.328, imgUrl: IMG.hero3 },
    ],
  },
  {
    slug: 'cherry-apartment-hue',
    name: 'Cherry Apartment Huế',
    city: 'Huế',
    region: 'Thừa Thiên Huế',
    kind: 'serviced_apartment',
    tagline: 'Căn hộ dịch vụ gần Kinh thành Huế',
    description: 'Căn hộ Cherry House tại Huế — phù hợp lưu trú dài ngày và khám phá di sản.',
    address: 'TP. Huế, Thừa Thiên Huế',
    priceFromVnd: 690_000,
    rating: 4.5,
    reviewCount: 124,
    heroImageUrl: IMG.hero2,
    highlights: ['Bếp riêng', 'Gần sông Hương'],
    branches: [
      { code: 'hue-river', name: 'Apartment Sông Hương', address: 'P. Phú Hội, TP. Huế', tagline: 'View sông buổi sáng', price: 690_000, roomCount: 8, lat: 16.4637, lng: 107.5909, imgUrl: IMG.hero2 },
      { code: 'hue-citadel', name: 'Apartment Kinh thành', address: 'P. Thuận Hòa, TP. Huế', tagline: 'Gần Đại Nội', price: 750_000, roomCount: 6, lat: 16.4698, lng: 107.5792, imgUrl: IMG.hero1 },
    ],
  },
  {
    slug: 'cherry-house-nha-trang',
    name: 'Cherry House Nha Trang',
    city: 'Nha Trang',
    region: 'Khánh Hòa',
    kind: 'mini_hotel',
    tagline: 'Mini hotel ven biển Nha Trang',
    description: 'Cherry House Nha Trang — nghỉ gần bãi biển và trung tâm thành phố biển.',
    address: 'TP. Nha Trang, Khánh Hòa',
    priceFromVnd: 850_000,
    rating: 4.6,
    reviewCount: 289,
    heroImageUrl: IMG.hero1,
    highlights: ['Gần bãi Trần Phú', 'Tour đảo'],
    branches: [
      { code: 'nt-beach', name: 'Chi nhánh Bãi biển', address: 'Đường Trần Phú, Nha Trang', tagline: 'View biển từ phòng Deluxe', price: 850_000, roomCount: 14, lat: 12.2388, lng: 109.1967, imgUrl: IMG.hero1 },
    ],
  },
  {
    slug: 'cherry-house-da-lat',
    name: 'Cherry House Đà Lạt',
    city: 'Đà Lạt',
    region: 'Lâm Đồng',
    kind: 'homestay',
    tagline: 'Homestay giữa thành phố ngàn hoa',
    description: 'Cherry House Đà Lạt — cụm homestay dưới thương hiệu Cherry House tại Lâm Đồng.',
    address: 'TP. Đà Lạt, Lâm Đồng',
    priceFromVnd: 890_000,
    rating: 4.8,
    reviewCount: 328,
    heroImageUrl: IMG.hero1,
    highlights: ['Khí hậu mát', 'Gần hồ Xuân Hương'],
    branches: [
      { code: 'dl-hxh', name: 'Chi nhánh Hồ Xuân Hương', address: 'Gần Hồ Xuân Hương, P.1', tagline: 'Yên tĩnh, gần hồ', price: 890_000, roomCount: 14, lat: 11.9404, lng: 108.4583, imgUrl: IMG.hero2 },
      { code: 'dl-dt', name: 'Chi nhánh Đồi Thông', address: 'Khu Đồi Thông', tagline: 'View rừng thông', price: 990_000, roomCount: 16, lat: 11.9521, lng: 108.4412, imgUrl: IMG.hero3 },
    ],
  },
  {
    slug: 'cherry-villa-vung-tau',
    name: 'Cherry Villa Vũng Tàu',
    city: 'Vũng Tàu',
    region: 'Bà Rịa - Vũng Tàu',
    kind: 'villa',
    tagline: 'Villa view biển — BBQ & hồ bơi',
    description: 'Cherry Villa Vũng Tàu — nguyên căn cho nhóm cuối tuần biển.',
    address: 'TP. Vũng Tàu, Bà Rịa - Vũng Tàu',
    priceFromVnd: 4_500_000,
    rating: 4.7,
    reviewCount: 56,
    heroImageUrl: IMG.hero4,
    highlights: ['Hồ bơi riêng', 'Gần bãi Back Beach'],
    branches: [
      { code: 'vt-sea', name: 'Villa Bãi Sau', address: 'P. Phước Tỉnh, Vũng Tàu', tagline: 'View biển panorama', price: 4_500_000, roomCount: 1, lat: 10.346, lng: 107.0843, imgUrl: IMG.hero4 },
    ],
  },
  {
    slug: 'cherry-house-saigon',
    name: 'Cherry House Sài Gòn',
    city: 'TP. Hồ Chí Minh',
    region: 'Hồ Chí Minh',
    kind: 'serviced_apartment',
    tagline: 'Căn hộ dịch vụ trung tâm Quận 1 & Thảo Điền',
    description: 'Cherry House tại TP.HCM — lưu trú tiện nghi cho công tác và city break.',
    address: 'Quận 1 & Quận 2, TP. Hồ Chí Minh',
    priceFromVnd: 980_000,
    rating: 4.6,
    reviewCount: 502,
    heroImageUrl: IMG.hero2,
    highlights: ['Gần metro', 'Workspace trong phòng'],
    branches: [
      { code: 'sg-q1', name: 'Chi nhánh Quận 1', address: 'P. Bến Nghé, Quận 1', tagline: 'Gần chợ Bến Thành', price: 980_000, roomCount: 11, lat: 10.7769, lng: 106.7009, imgUrl: IMG.hero2 },
      { code: 'sg-td', name: 'Chi nhánh Thảo Điền', address: 'P. Thảo Điền, Quận 2', tagline: 'Khu expat, quán cà phê', price: 1_150_000, roomCount: 9, lat: 10.8031, lng: 106.7317, imgUrl: IMG.hero3 },
    ],
  },
];

/** 5 phòng mẫu — thêm sau trong admin */
const SAMPLE_ROOMS = [
  {
    propertySlug: 'cherry-house-ha-noi',
    branchCode: 'hn-hk',
    code: 'HN-101',
    roomTypeSlug: 'standard-garden',
    priceVnd: 750_000,
    description: 'Phòng 101 — view phố, tầng 2',
    altText: 'Standard Hà Nội 101',
    status: 'available',
  },
  {
    propertySlug: 'cherry-house-da-nang',
    branchCode: 'dn-mykhe',
    code: 'MK-201',
    roomTypeSlug: 'deluxe-pine',
    priceVnd: 1_050_000,
    description: 'Deluxe hướng biển — tầng 2',
    altText: 'Deluxe Mỹ Khê 201',
    status: 'available',
  },
  {
    propertySlug: 'cherry-house-hoi-an',
    branchCode: 'ha-oldtown',
    code: 'HA-01',
    roomTypeSlug: 'standard-garden',
    priceVnd: 820_000,
    description: 'Phòng phố cổ — ban công nhỏ',
    altText: 'Standard Hội An',
    status: 'pending',
  },
  {
    propertySlug: 'cherry-house-da-lat',
    branchCode: 'dl-hxh',
    code: 'HXH-101',
    roomTypeSlug: 'standard-garden',
    priceVnd: 890_000,
    description: 'Phòng 101 — tầng 1, view vườn',
    altText: 'Standard Garden 101',
    status: 'available',
  },
  {
    propertySlug: 'cherry-house-saigon',
    branchCode: 'sg-q1',
    code: 'Q1-305',
    roomTypeSlug: 'deluxe-pine',
    priceVnd: 1_100_000,
    description: 'Căn studio Quận 1 — có bếp',
    altText: 'Deluxe Sài Gòn Q1',
    status: 'booked',
  },
];

const ROOM_TYPES = [
  {
    slug: 'standard-garden',
    badge: 'Phổ thông',
    title: 'Standard Garden View',
    category: 'Standard',
    areaSqm: 22,
    bedLabel: '1 giường đôi',
    capacityLabel: '2 người lớn',
    basePriceVnd: 750_000,
    paragraphs: ['Phòng tiêu chuẩn view vườn hoặc phố.', 'Phù hợp cặp đôi hoặc solo.'],
    policyBullets: ['Check-in 14:00', 'Check-out 12:00', 'Không hút thuốc'],
  },
  {
    slug: 'deluxe-pine',
    badge: 'Cao cấp',
    title: 'Deluxe View',
    category: 'Deluxe',
    areaSqm: 32,
    bedLabel: '1 giường king',
    capacityLabel: '2 người lớn + 1 trẻ em',
    basePriceVnd: 1_100_000,
    paragraphs: ['Phòng deluxe view rộng hơn.'],
    policyBullets: ['Check-in 14:00', 'Miễn phí bãi đỗ xe'],
  },
];

const AMENITIES = [
  { icon: 'wifi', label: 'Wi-Fi miễn phí' },
  { icon: 'parking', label: 'Bãi đỗ xe' },
  { icon: 'breakfast', label: 'Bữa sáng' },
  { icon: 'ac', label: 'Điều hòa' },
  { icon: 'pool', label: 'Hồ bơi' },
];

module.exports = {
  IMG,
  BRANCH_COUNTS,
  PROPERTIES,
  SAMPLE_ROOMS,
  ROOM_TYPES,
  AMENITIES,
};
